const fs = require('fs');
const artRaw = require('./raw.json');

const liveArt = artRaw.filter(artwork => artwork.name && artwork.slug && artwork.date);

function processArtData(artwork) {
  let { showcase, spotlight } = artwork;
  showcase = !!showcase;
  spotlight = !!spotlight;
  const tags = artwork.tags.split(',');

  return {
    ...artwork,
    showcase,
    spotlight,
    tags,
  };
}

const artProcessed = liveArt.map(processArtData);

const allTags = artProcessed
  .map(artwork => artwork.tags)
  .flat()
  .filter(tag => tag !== '');

const CATEGORIES = new Set(allTags);

const outputFile = 'src/data/art.js';

const outputString = `
// file generated by process/script.js

const art = ${JSON.stringify(artProcessed)};

export const CATEGORIES = ${JSON.stringify([...CATEGORIES])};

export default art;
`;

fs.writeFile(outputFile, outputString, function (err) {
  if (err) return console.log(err);
  console.log(`Art data written to file ${outputFile}`);
});
